; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_deps = 
	hoeken/YarrboardFramework@^2.6.2
	; https://github.com/hoeken/YarrboardFramework
	; symlink://../YarrboardFramework
	RobTillaart/ADS1X15
	stevemarple/MCP342x
	https://github.com/hoeken/Arduino_MCP3x6x_Library
platform=https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework=arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
extra_scripts = 
	pre:scripts/yarrboard_framework.py
board_build.embed_txtfiles=ca_cert_bundle

; for PsychicHttp or other lib development (add to lib_deps)
; symlink://../YarrboardFramework

; typical mac ports
; upload_port=/dev/cu.usbmodem21101
; monitor_port=/dev/cu.usbmodem58CD1802781

; typical linux ports
; upload_port=/dev/ttyACM0
; monitor_port=/dev/ttyACM1

; OTA Upload Config, auth password is admin password
; upload_protocol = espota
; upload_port = sendit.local
; upload_flags = 
; 	--auth=admin
; 	--port=3232


[env:SENDIT_REV_C]
board=esp32-s3-devkitc-1 
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.use_usb = true
board_build.usb_cdc_on_boot = true
build_type=debug
build_flags = ${env.build_flags}
	-D YB_CONFIG_SENDIT_REV_C
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D IMPROV_WIFI_BLE_ENABLED
lib_deps = ${env.lib_deps}
	RobTillaart/ADS1X15
	h2zero/NimBLE-Arduino
;
; OBSOLETE BUILD TARGETS BELOW HERE
;

; [env:SENDIT_REV_A]
; framework=arduino
; board=esp32-s3-devkitc-1
; build_type=debug
; board_build.partitions = default_8MB.csv
; build_flags = ${env.build_flags}
;     -D YB_CONFIG_SENDIT_REV_A
; 		-D IMPROV_WIFI_BLE_ENABLED
; upload_port = /dev/cu.usbmodem21201
; monitor_port = /dev/cu.usbmodem5A671708601
; lib_deps = ${env.lib_deps}
; 		h2zero/NimBLE-Arduino

; [env:SENDIT_REV_B]
; framework=arduino
; board=esp32-s3-devkitc-1
; build_type=debug
; board_build.partitions = default_16MB.csv
; build_flags = ${env.build_flags}
;     -D YB_CONFIG_SENDIT_REV_B